name: "Push To Itch"
description: "Pushes your project to Itch using Butler"
inputs:
  BUTLER_API_KEY:
    description: "Your Butler API Key. Best to use GitHub secrets."
    required: true
  PACKAGE:
    description: "What you want uploaded"
    required: true
  USER:
    description: "Your Itch Username"
    required: true
  GAME_NAME:
    description: "The name of your game page"
    required: true
  CHANNEL:
    description: "The slot you are uploading your project to"
    required: true
  
  runs:
    using: "composite"
    steps:
      - name: Install Butler
        run: echo "curl -L -o butler.zip https://broth.itch.zone/butler/linux-amd64/LATEST/archive/default && unzip butler.zip && cp butler /usr/bin && chmod +x /usr/bin/butler"
        shell: bash
      
      - name: Push to Itch
        run: echo "butler push -i $BUTLER_API_KEY $PACKAGE $USER/$GAME_NAME:$CHANNEL"
        shell: bash
  