name: "Butler Upload"
description: "Uploads project to itch using butler"

runs:
  using: "composite"
  steps:
    - name: Install Butler
      run: echo "curl -L -o butler.zip https://broth.itch.zone/butler/linux-amd64/LATEST/archive/default && unzip butler.zip && cp butler /usr/bin && chmod +x /usr/bin/butler"
      shell: bash