name: "Push To Itch"
description: "Pushes your project to Itch using Butler"
inputs:
  BUTLER_API_KEY:
    description: "Your Butler API Key. Best to use GitHub secrets."
    required: true
  PACKAGE:
    description: "What you want uploaded"
    required: true
  USER:
    description: "Your Itch Username"
    required: true
  GAME_NAME:
    description: "The name of your game page"
    required: true
  CHANNEL:
    description: "The slot you are uploading your project to"
    required: true
  VERSION:
    description: "Version of the game"
    required: true
  
runs:
  using: "composite"
  steps:
    - name: Install Butler
      run: curl -L -o butler.zip https://broth.itch.zone/butler/linux-amd64/LATEST/archive/default && unzip butler.zip butler && chmod +x butler
      shell: bash
    - name: Push to Itch
      run: ./butler push $PACKAGE $USER/$GAME_NAME:$CHANNEL --userversion=$VERSION --identity=$BUTLER_API_KEY
      shell: bash
  