name: Build Unity Project

on: 
  workflow_dispatch:
  schedule:
    - cron: "30 6 * * *" # every day at 6:30AM UTC (2:30AM EST)

jobs:
  build:
    name: Build for Windows Standalone
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targetPlatform:
          - StandaloneOSX
          - StandaloneWindows
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Cache library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-

      - name: Build project
        id: build
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
      
      - name: Write Matrices
        uses: cloudposse/github-action-matrix-outputs-write@v1
        id: out
        with:
          matrix-step-name: ${{ github.job }}
          matrix-key: ${{ matrix.targetPlatform }}
          outputs: |-
            buildPath: build/${{matrix.targetPlatform}}
    
  read:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: cloudposse/github-action-matrix-outputs-read@v1
        id: read
        with:
          matrix-step-name: build
    outputs:
      result: "${{ steps.read.outputs.result }}"
        
  push:
    name: Push Windows Build to Itch
    runs-on: ubuntu-latest
    needs: [read]
    strategy:
      matrix:
        targetPlatform:
          - macos
          - win
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Builds path sanity check
        run: ls && echo "${{ needs.read.outputs.result }}"
        shell: bash

      - name: Push to Itch
        uses: ./actions/push-to-itchio
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
          PACKAGE: ${{ (needs.read.outputs.result).buildPath }}
          USER: acour008
          GAME_NAME: testci
          CHANNEL: ${{ matrix.targetPlatform }}
          