name: Build Unity Project

on: workflow_dispatch
#  schedule:
#    - cron: "30 6 * * *" # every day at 6:30AM UTC (2:30 EST)

env:
  WIN_64_BUILD_PATH: build/windows-64bit
  MAC_BUILD_PATH: build/macos

runs:
  using: 'node20'
  main: 'main.js'

jobs:
  build:
    name: Build for Windows Standalone
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache Library folder
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows

      - uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: $$ {{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: windows
          ITCH_GAME: testci
          ITCH_USER: ACour008
          PACKAGE: $WIN_64_BUILD_PATH