name: Build and Push Unity Projects

on: 
  workflow_dispatch:
  schedule:
    - cron: "30 6 * * *" # every day at 6:30AM UTC (2:30AM EST)

jobs:
  build-win:
    name: Build Windows Standalone
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          lfs: true
      
      - name: Cache library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Build
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows
      
      - name: Sanity Check
        run: ls build
        shell: bash

      - name: Push
        uses: ./actions/push-to-itchio
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
          PACKAGE: build/
          USER: acour008
          GAME_NAME: testci
          CHANNEL: win         

  build-osx:
    name: Build MacOS X Standalone
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          lfs: true
      
      - name: Cache library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Build
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneOSX
      
      - name: Sanity Check
        run: ls build
        shell: bash

      - name: Push
        uses: ./actions/push-to-itchio
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
          PACKAGE: build/
          USER: acour008
          GAME_NAME: testci
          CHANNEL: os