name: Build Unity Project

on: workflow_dispatch
#  schedule:
#    - cron: "30 6 * * *" # every day at 6:30AM UTC (2:30 EST)

env:
  WIN_64_BUILD_PATH: build/windows-64bit
  MAC_BUILD_PATH: build/macos

jobs:
  build:
    name: Build for Windows Standalone
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          lfs: true
      
      - name: Download butler
        uses: ./